#!/bin/bash
#: Title			: baksize
#: Date				: October 2013
#: Author			: Sharon Kimble
#: Version			: 1.5
#: Description			: script to show obnam backup sizes in conky.
#: License			: GNU GPL 3.0 or later
####################################################
# How to use.
# Put this line into your conky script where you want the totals to show, and amending the line as to where you've stored 'baksize'
# BACKUP : ${execi 300 ~/bin/baksize}
####################################################

echo 'Obnam-back4' - `( du -sh /media/backup/obnam-back4 |awk '{ print $1; }' )`

echo 'Obnam-home' - `( du -sh /media/backup/obnam-home2 |awk '{ print $1; }' )`
