#!/bin/bash
#: Title				: unlock
#: Date				: November 2013
#: Author				: Sharon Kimble
#: Version			: 2.1
#: Description			: to remove all 'lock' files from my obnam backup files
#: Options			: 8, as listed in variables
#: License			: GNU GPL 3.0 or later
####################################################
# Change log 
# 3-10-13 
#	* Initial release
# 4-10-13
#	* Started logging
# 7-11-13
#	* cleaned up the script
#	* added in obnam-back4
################################################### 
# Variables 
chunk="/media/boudiccas/backup/obnam-home2"	#site of backup files
chunk2="/media/boudiccas/backup/obnam-back4"	#site of backup4 files
bignum="5042396860350391879"	#unique id number of backup series
bignum2="5068550679861121148"	#unique id number of backup4 series
logto="/home/boudiccas/logs/unlock-$(/bin/date +%Y%m%d-%R).txt"	#log of where lock-file isn't
mainlog="/home/boudiccas/logs/obnam.txt" #main log of backup where everything is logged
sender="$user@localhost"
subj="Files unlocked."
####################################################
{
    rm "$chunk"/chunklist/lock
    rm "$chunk"/"$bignum"/lock
    rm "$chunk"/chunksums/lock 
    rm "$chunk"/chunks/lock 
    rm "$chunk"/clientlist/lock 
    rm "$chunk"/metadata/lock
} 2> >(tee "$logto" | tee -a "$mainlog" > /dev/tty ) | tee outlog | tee -a "$mainlog"

mailx -s "$subj" boudiccas@localhost < "$logto"

{
    rm "$chunk2"/chunklist/lock
    rm "$chunk2"/"$bignum2"/lock
    rm "$chunk2"/chunksums/lock 
    rm "$chunk2"/chunks/lock 
    rm "$chunk2"/clientlist/lock 
    rm "$chunk2"/metadata/lock
} 2> >(tee "$logto" | tee -a "$mainlog" > /dev/tty ) | tee outlog | tee -a "$mainlog"

mailx -s "$subj" boudiccas@localhost < "$logto"
