#!/usr/bin/env bash
#: Title			: backup
#: Date				: July 2013
#: Author			: Keith Edwards (GLLUG), Moggers87, and Sharon Kimble.
#: Version			: 5.6
#: Description			: Backs up and retains a certain number of days worth before deleting them in a cycle. Works with rsync from the users crontab.
#: Options			: Nine options, all shown under '# Variables'.
#: License			: GNU GPL 3.0 or later
####################################################
# CHANGELOG.
# v5.5 [30-6-2013]
# Added in LOG_FILE.
# Released under GNU GPL 3.
# v5.6 [8-7-2013]
# Changed 'USB_DIR' to reflect the change in saving of files on Debian and Thunar
# removed '--exclude-from '/home/boudiccas/cron/xclude.txt' \' as no longer needed.
# v5.7 [28-10-2013]
# Added in $user name into file path to conform with xfce requirements.
####################################################
# Variables
home_dir="/home/boudiccas/cron"
usb_dir="/media/boudiccas/backup/back/cron"
backup_dir="$usb_dir/$(/bin/date +%Y%m%d)"
email="boudiccas@localhost"
subject="Backup Error"
email_message="Couldn't find $usb_dir, are you sure its plugged in or mounted?"
num_left="14" #number of days backups to hold
log_file="/home/boudiccas/logs/backup.txt"
####################################################
# Don't change anything after here.

# Check if rsync still running
if pgrep -f 'rsync.*/home/'; then echo "E: old rsync still running" 1>&2; exit 1; fi

# Backup files
if [ -d $home_dir ] & [ -d $usb_dir ]; then
   [ -d $backup_dir ] || mkdir $backup_dir \
   >> $log_file 2>&1
   /usr/bin/rsync  -avzP /home/boudiccas/cron $backup_dir \
   >>$log_file 2>&1
   
   # Delete those old backups! Yeah!
   (find $usb_dir -maxdepth 1 -type d -name "20*" | sort | tail -n $num_left; \
   find $usb_dir -maxdepth 1 -type d -name "20*") | \
   sort | uniq -u | xargs -n1 rm -rf \
   >>$log_file 2>&1
else
   # Send an email
   /bin/mail -s "$subject" "$email" < "$email_message"
   
   #kill all unwanted rsync programmes
   /usr/bin/killall rsync
   
echo 'backup finished', $backup_dir

fi
