#!/bin/bash
#: Title	        	: fluxmenu
#: Date				: November 2013
#: Author		        : Sharon Kimble
#: Version			: 4.0
#: Times edited			: 24
#: Description			: to easily show a list of programmes, choose one and install it, and then update the 'universal database', and generate a complete fluxbox menu.
#: Options			: 1, as listed in variables
#; Requirements			: menumaker-0.99.7.tar.gz, in the /programmes directory
#: License			: GNU GPL 3.0 or later
####################################################
# Changelog.
# * 17-11-13 - initial version of the script, logs output, added ability to install, and update
# the universal database.
# * 18-11-13 - added the ability to generate a fluxbox menu.
# * 19-11-13 - added the ability to quit part-way through
# * 22-11-13 - the menu now includes your 'usermenu'
# * 23-11-13 - has the ability to install more than one programme at a time.
# * 25-11-13 - now excludes all xscreensaver entries from the main menu when its generated. 
####################################################
# Variables
logprogramme="/home/boudiccas/logs/want.txt"
####################################################
exec > >(tee -a $logprogramme) 2>&1

# Searches the apt-cache
echo "What programmes would you like to see? One word answer please!"
echo
read programme
echo
apt-cache search programme
echo

# Uses apt-cache policy to show info regarding one programme
echo "What programme do you want to see more information of? "
echo
read "$programme"
echo
apt-cache show "$programme" | grep -i description -A 8

apt-cache policy "$programme"	#shows whether installed or not, and repo of it.

echo 
{	
	read -p "Do you want to install more than one programme? If you answer 'n' then you will install your choice [y/n/q] " ynq
    case $ynq in
        [Yy]* ) echo;; 
        [Nn]* ) sudo apt-get install "$programme";;
	[Qq]* ) exit;;
        * ) echo "Please answer yes or no. ";;
    esac
}

# Uses apt-cache policy to show info regarding one or more programmes
echo "What programmes do you want to see more information of? Please leave a space between each programme. "
echo
read "$programme"
echo
apt-cache show "$programme" 

apt-cache policy "$programme"	#shows whether installed or not, and repo of it.

# Install them?
echo 
{	
	read -p "Do you want to install these programmes? [y/n/q] " ynq
    case $ynq in
        [Yy]* ) sudo apt-get install "$programme";; 
        [Nn]* ) echo;;
	[Qq]* ) exit;;
        * ) echo "Please answer yes or no. ";;
    esac
}
# use updatedb
echo
{    
	read -p "Do you want to update the universal database? [y/n/q] " ynq
   case $ynq in
        [Yy]* ) sudo updatedb;;
        [Nn]* ) echo;;
	[Qq]* ) exit;;
        * ) echo "Please answer yes or no. ";;
    esac
}

echo
{    
	read -p "Do you want to update the fluxbox menu? [y/n] " yn
   case $yn in
        [Yy]* ) mv ~/.fluxbox/menu{,-$(date +%Y%m%d-%R)}; mmaker fluxbox -f; sed -i '\|\[exec[]]\s[(].*[)]\s[{]/usr/lib/xscreensaver/.*\s-root[}]|d' ~/.fluxbox/menu; sed -i '\|\[exec[]]\s[(].*[)]\s[{]\b\(xscreensaver\).*[}]|d' ~/.fluxbox/menu; perl -0777 -pi -e 's/(.*)\[end]/$1/s;s/(.*)\[end]/$1/s;s/^\s*\n//gm' ~/.fluxbox/menu; printf '\t[end]\n\t[separator]\n\t[submenu] (My Menu)\n\t[include] (~/.fluxbox/usermenu)\n\t[end]\n\t[end]' >>~/.fluxbox/menu;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no. ";;
    esac
}
exit